In [42]:
import pandas as pd
import numpy as np

The  LendingClub provides accepted and rejected loan data.
The data is in two csv files, one for accepted cases and another for rejected cases.
The data is from 2007 to 2018 Q4.
We will be focusing only on accepted data as our primary focus is on:
- funded loans
- borrower information
- loan outcomes

In [43]:
# Reading accepted data
data = pd.read_csv('../../data/original/lending-club/accepted_2007-2018Q4.csv', low_memory=False)

In [44]:
data.shape

(2260701, 151)

In [45]:
data.head(3)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
data.columns.tolist()

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'url',
 'desc',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'fico_range_low',
 'fico_range_high',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'last_fico_range_high',
 'last_fico_range_low',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_act_il',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'revol_bal_joint',
 'sec_app_fico_range_low',
 'sec_app_fico_range_high',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'disbursement_method',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

In [47]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Columns: 151 entries, id to settlement_term
dtypes: float64(113), object(38)
memory usage: 2.5+ GB

In [48]:
data.describe()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,...,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,0.0,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260664e+06,2.258957e+06,2.260639e+06,2.260668e+06,...,10917.0,10917.000000,10917.0,10917.000000,8651.000000,10917.000000,10917.000000,34246.000000,34246.000000,34246.000000
mean,NaN,1.504693e+04,1.504166e+04,1.502344e+04,1.309283e+01,4.458068e+02,7.799243e+04,1.882420e+01,3.068792e-01,6.985882e+02,...,3.0,155.045981,3.0,13.743886,454.798089,11636.883942,193.994321,5010.664267,47.780365,13.191322
std,NaN,9.190245e+03,9.188413e+03,9.192332e+03,4.832138e+00,2.671735e+02,1.126962e+05,1.418333e+01,8.672303e-01,3.301038e+01,...,0.0,129.040594,0.0,9.671178,375.385500,7625.988281,198.629496,3693.122590,7.311822,8.159980
min,NaN,5.000000e+02,5.000000e+02,0.000000e+00,5.310000e+00,4.930000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,6.100000e+02,...,3.0,0.640000,3.0,0.000000,1.920000,55.730000,0.010000,44.210000,0.200000,0.000000
25%,NaN,8.000000e+03,8.000000e+03,8.000000e+03,9.490000e+00,2.516500e+02,4.600000e+04,1.189000e+01,0.000000e+00,6.750000e+02,...,3.0,59.440000,3.0,5.000000,175.230000,5627.000000,44.440000,2208.000000,45.000000,6.000000
50%,NaN,1.290000e+04,1.287500e+04,1.280000e+04,1.262000e+01,3.779900e+02,6.500000e+04,1.784000e+01,0.000000e+00,6.900000e+02,...,3.0,119.140000,3.0,15.000000,352.770000,10028.390000,133.160000,4146.110000,45.000000,14.000000
75%,NaN,2.000000e+04,2.000000e+04,2.000000e+04,1.599000e+01,5.933200e+02,9.300000e+04,2.449000e+01,0.000000e+00,7.150000e+02,...,3.0,213.260000,3.0,22.000000,620.175000,16151.890000,284.190000,6850.172500,50.000000,18.000000
max,NaN,4.000000e+04,4.000000e+04,4.000000e+04,3.099000e+01,1.719830e+03,1.100000e+08,9.990000e+02,5.800000e+01,8.450000e+02,...,3.0,943.940000,3.0,37.000000,2680.890000,40306.410000,1407.860000,33601.000000,521.350000,181.000000

# Key Columns Identification

loan_status -- Loan Outcome (for approval proxy)
int_rate    -- Used for APR prediction

🔹 Loan Features
 - loan_amnt
 - term
 - installment

🔹 Borrower Features
 - annual_inc
 - emp_length
 - home_ownership

🔹 Credit Features
 - fico_range_low
 - fico_range_high
 - delinq_2yrs
 - inq_last_6mths
 - earliest_cr_line

🔹 Behavioral Features
 - revol_util
 - total_acc

In [49]:
cols = [
    # Targets
    'int_rate', 'loan_status',

    # Loan
    'loan_amnt', 'term', 'installment',

    # Income
    'annual_inc', 'verification_status',

    # Employment
    'emp_length',

    # Credit risk
    'dti', 'fico_range_low', 'fico_range_high',
    'delinq_2yrs', 'inq_last_6mths',

    # Revolving credit
    'revol_util', 'revol_bal',

    # Credit depth
    'total_acc', 'open_acc', 'pub_rec',

    # History
    'earliest_cr_line',

    # Behavioral
    'purpose'
]

In [50]:
df_lc = data[cols].copy()

In [51]:
print(df_lc.shape)
print(df_lc.head())

(2260701, 20)
   int_rate loan_status  loan_amnt        term  installment  annual_inc  \
0     13.99  Fully Paid     3600.0   36 months       123.03     55000.0
1     11.99  Fully Paid    24700.0   36 months       820.28     65000.0
2     10.78  Fully Paid    20000.0   60 months       432.66     63000.0
3     14.85     Current    35000.0   60 months       829.90    110000.0
4     22.45  Fully Paid    10400.0   60 months       289.91    104433.0

  verification_status emp_length    dti  fico_range_low  fico_range_high  \
0        Not Verified  10+ years   5.91           675.0            679.0
1        Not Verified  10+ years  16.06           715.0            719.0
2        Not Verified  10+ years  10.78           695.0            699.0
3     Source Verified  10+ years  17.06           785.0            789.0
4     Source Verified    3 years  25.37           695.0            699.0

   delinq_2yrs  inq_last_6mths  revol_util  revol_bal  total_acc  open_acc  \
0          0.0             1.0        29.7     2765.0       13.0       7.0
1          1.0             4.0        19.2    21470.0       38.0      22.0
2          0.0             0.0        56.2     7869.0       18.0       6.0
3          0.0             0.0        11.6     7802.0       17.0      13.0
4          1.0             3.0        64.5    21929.0       35.0      12.0

   pub_rec earliest_cr_line             purpose
0      0.0         Aug-2003  debt_consolidation
1      0.0         Dec-1999      small_business
2      0.0         Aug-2000    home_improvement
3      0.0         Sep-2008  debt_consolidation
4      0.0         Jun-1998      major_purchase

In [52]:
df_lc.isnull().sum().sort_values(ascending=False)

emp_length             146940
revol_util               1835
dti                      1744
inq_last_6mths             63
earliest_cr_line           62
pub_rec                    62
open_acc                   62
total_acc                  62
delinq_2yrs                62
annual_inc                 37
int_rate                   33
revol_bal                  33
fico_range_high            33
loan_status                33
fico_range_low             33
verification_status        33
installment                33
term                       33
loan_amnt                  33
purpose                    33
dtype: int64

# Target Processing

In [53]:
df_lc["loan_status"].value_counts()

loan_status
Fully Paid                                             1076751
Current                                                 878317
Charged Off                                             268559
Late (31-120 days)                                       21467
In Grace Period                                           8436
Late (16-30 days)                                         4349
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     40
Name: count, dtype: int64

GOOD LOANS (0)
 - Fully Paid
 - Does not meet the credit policy. Status:Fully Paid

BAD LOANS (1)
 - Charged Off
 - Does not meet the credit policy. Status:Charged Off
 - Late (31-120 days)
 - Late (16-30 days)
 - Default

REMOVE ONGOING LOANS
 - Current
 - In Grace Period

In [54]:
valid_status = [
    "Fully Paid",
    "Charged Off",
    "Late (31-120 days)",
    "Late (16-30 days)",
    "Default",
    "Does not meet the credit policy. Status:Fully Paid",
    "Does not meet the credit policy. Status:Charged Off"
]

df_lc = df_lc[df_lc["loan_status"].isin(valid_status)]

In [55]:
bad_status = [
    "Charged Off",
    "Late (31-120 days)",
    "Late (16-30 days)",
    "Default",
    "Does not meet the credit policy. Status:Charged Off"
]

df_lc["target"] = df_lc["loan_status"].apply(
    lambda x: 1 if x in bad_status else 0
)

df_lc.drop("loan_status", axis=1, inplace=True)

df_lc["target"].value_counts()
df_lc["target"].value_counts(normalize=True)

target
0    0.785157
1    0.214843
Name: proportion, dtype: float64

In [56]:
df_lc.columns

Index(['int_rate', 'loan_amnt', 'term', 'installment', 'annual_inc',
       'verification_status', 'emp_length', 'dti', 'fico_range_low',
       'fico_range_high', 'delinq_2yrs', 'inq_last_6mths', 'revol_util',
       'revol_bal', 'total_acc', 'open_acc', 'pub_rec', 'earliest_cr_line',
       'purpose', 'target'],
      dtype='object')

In [57]:
df_lc.head(3)

,int_rate,loan_amnt,term,installment,annual_inc,verification_status,emp_length,dti,fico_range_low,fico_range_high,delinq_2yrs,inq_last_6mths,revol_util,revol_bal,total_acc,open_acc,pub_rec,earliest_cr_line,purpose,target
0,13.99,3600.0,36 months,123.03,55000.0,Not Verified,10+ years,5.91,675.0,679.0,0.0,1.0,29.7,2765.0,13.0,7.0,0.0,Aug-2003,debt_consolidation,0
1,11.99,24700.0,36 months,820.28,65000.0,Not Verified,10+ years,16.06,715.0,719.0,1.0,4.0,19.2,21470.0,38.0,22.0,0.0,Dec-1999,small_business,0
2,10.78,20000.0,60 months,432.66,63000.0,Not Verified,10+ years,10.78,695.0,699.0,0.0,0.0,56.2,7869.0,18.0,6.0,0.0,Aug-2000,home_improvement,0

# Data Cleaning

In [58]:
# Drop Rows with Critical Missing

df_lc = df_lc.dropna(subset=[
    "target",
    "int_rate",
    "loan_amnt",
    "term",
    "installment",
    "annual_inc",
    "fico_range_low",
    "fico_range_high",
    "dti",
])

In [59]:
num_cols = [
    'revol_bal',
    'inq_last_6mths',
    'open_acc',
    'total_acc',
    'pub_rec',
    'delinq_2yrs',
    'revol_util'
]

df_lc[num_cols] = df_lc[num_cols].fillna(df_lc[num_cols].median())

In [60]:
# Clean term
df_lc["term"] = df_lc["term"].str.extract(r'(\d+)').astype(int)

In [61]:
# Create fico_score
df_lc["fico_score"] = (
    df_lc["fico_range_low"] + df_lc["fico_range_high"]
) / 2

df_lc.drop(["fico_range_low", "fico_range_high"], axis=1, inplace=True)

In [62]:
# Convert earliest_cr_line tp credit_history_length
df_lc["credit_history_length"] = (
    pd.to_datetime("today") -
    pd.to_datetime(
        df_lc["earliest_cr_line"],
        format="%b-%Y",
        errors="coerce"
    )
).dt.days / 365

df_lc.drop("earliest_cr_line", axis=1, inplace=True)

In [63]:
# Clean emp_length
df_lc["emp_length"] = (
    df_lc["emp_length"]
    .str.extract(r'(\d+)')
    .astype(float)
)

df_lc["emp_length"] = df_lc["emp_length"].fillna(-1)

In [64]:
df_lc["inq_last_6mths"] = df_lc["inq_last_6mths"].fillna(0)
df_lc["delinq_2yrs"] = df_lc["delinq_2yrs"].fillna(0)
df_lc["total_acc"] = df_lc["total_acc"].fillna(df_lc["total_acc"].median())

In [65]:
df_lc = df_lc.replace([float('inf'), -float('inf')], pd.NA)

In [66]:
df_lc["credit_history_length"] = df_lc["credit_history_length"].fillna(
    df_lc["credit_history_length"].median()
)

In [67]:
cat_cols = ['purpose','verification_status']
df_lc[cat_cols] = df_lc[cat_cols].fillna('Unknown')

In [68]:
df_lc.isnull().sum().sort_values(ascending=False)

int_rate                 0
revol_util               0
fico_score               0
target                   0
purpose                  0
pub_rec                  0
open_acc                 0
total_acc                0
revol_bal                0
inq_last_6mths           0
loan_amnt                0
delinq_2yrs              0
dti                      0
emp_length               0
verification_status      0
annual_inc               0
installment              0
term                     0
credit_history_length    0
dtype: int64

In [69]:
df_lc.shape

(1373508, 19)

In [70]:
df_lc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1373508 entries, 0 to 2260697
Data columns (total 19 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   int_rate               1373508 non-null  float64
 1   loan_amnt              1373508 non-null  float64
 2   term                   1373508 non-null  int64
 3   installment            1373508 non-null  float64
 4   annual_inc             1373508 non-null  float64
 5   verification_status    1373508 non-null  object
 6   emp_length             1373508 non-null  float64
 7   dti                    1373508 non-null  float64
 8   delinq_2yrs            1373508 non-null  float64
 9   inq_last_6mths         1373508 non-null  float64
 10  revol_util             1373508 non-null  float64
 11  revol_bal              1373508 non-null  float64
 12  total_acc              1373508 non-null  float64
 13  open_acc               1373508 non-null  float64
 14  pub_rec                1373508 non-null  float64
 15  purpose                1373508 non-null  object
 16  target                 1373508 non-null  int64
 17  fico_score             1373508 non-null  float64
 18  credit_history_length  1373508 non-null  float64
dtypes: float64(15), int64(2), object(2)
memory usage: 209.6+ MB

In [71]:
df_lc.describe()

,int_rate,loan_amnt,term,installment,annual_inc,emp_length,dti,delinq_2yrs,inq_last_6mths,revol_util,revol_bal,total_acc,open_acc,pub_rec,target,fico_score,credit_history_length
count,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06
mean,1.328534e+01,1.445720e+04,4.186296e+01,4.389718e+02,7.628202e+04,5.630152e+00,1.830763e+01,3.185653e-01,6.615564e-01,5.177206e+01,1.624851e+04,2.494231e+01,1.159165e+01,2.154592e-01,2.148338e-01,6.980898e+02,2.702907e+01
std,4.787062e+00,8.742497e+03,1.031197e+01,2.621425e+02,7.026271e+04,3.832357e+00,1.132211e+01,8.798839e-01,9.586877e-01,2.453097e+01,2.242656e+04,1.200980e+01,5.483222e+00,6.038865e-01,4.107072e-01,3.180762e+01,7.628341e+00
min,5.310000e+00,5.000000e+02,3.600000e+01,4.930000e+00,1.600000e+01,-1.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.120000e+02,1.047945e+01
25%,9.750000e+00,8.000000e+03,3.600000e+01,2.488800e+02,4.576000e+04,2.000000e+00,1.179000e+01,0.000000e+00,0.000000e+00,3.340000e+01,5.926000e+03,1.600000e+01,8.000000e+00,0.000000e+00,0.000000e+00,6.720000e+02,2.173699e+01
50%,1.279000e+01,1.200000e+04,3.600000e+01,3.754300e+02,6.500000e+04,6.000000e+00,1.763000e+01,0.000000e+00,0.000000e+00,5.210000e+01,1.111700e+04,2.300000e+01,1.100000e+01,0.000000e+00,0.000000e+00,6.920000e+02,2.565479e+01
75%,1.602000e+01,2.000000e+04,3.600000e+01,5.817700e+02,9.000000e+04,1.000000e+01,2.408000e+01,0.000000e+00,1.000000e+00,7.070000e+01,1.973600e+04,3.200000e+01,1.400000e+01,0.000000e+00,0.000000e+00,7.120000e+02,3.091233e+01
max,3.099000e+01,4.000000e+04,6.000000e+01,1.719830e+03,1.099920e+07,1.000000e+01,9.990000e+02,3.900000e+01,3.300000e+01,8.923000e+02,2.904836e+06,1.760000e+02,9.000000e+01,8.600000e+01,1.000000e+00,8.475000e+02,9.203562e+01

In [72]:
df_lc.head()

,int_rate,loan_amnt,term,installment,annual_inc,verification_status,emp_length,dti,delinq_2yrs,inq_last_6mths,revol_util,revol_bal,total_acc,open_acc,pub_rec,purpose,target,fico_score,credit_history_length
0,13.99,3600.0,36,123.03,55000.0,Not Verified,10.0,5.91,0.0,1.0,29.7,2765.0,13.0,7.0,0.0,debt_consolidation,0,677.0,22.654795
1,11.99,24700.0,36,820.28,65000.0,Not Verified,10.0,16.06,1.0,4.0,19.2,21470.0,38.0,22.0,0.0,small_business,0,717.0,26.323288
2,10.78,20000.0,60,432.66,63000.0,Not Verified,10.0,10.78,0.0,0.0,56.2,7869.0,18.0,6.0,0.0,home_improvement,0,697.0,25.654795
4,22.45,10400.0,60,289.91,104433.0,Source Verified,3.0,25.37,1.0,3.0,64.5,21929.0,35.0,12.0,0.0,major_purchase,0,697.0,27.824658
5,13.44,11950.0,36,405.18,34000.0,Source Verified,4.0,10.20,0.0,0.0,68.4,8822.0,6.0,5.0,0.0,debt_consolidation,0,692.0,38.498630

# Feature Engineering

Create Core Engineered Features

In [73]:
# Debt to income - How much income is used to repay loan
df_lc["dti_computed"] = (df_lc["installment"] * 12) / (df_lc["annual_inc"] + 1)

In [74]:
# Loan to income - Size of loan relative to income
df_lc["loan_to_income"] = df_lc["loan_amnt"] / (df_lc["annual_inc"] + 1)

In [75]:
# Normalize Credit Score - Keeps consistency with L&T later
df_lc["credit_score_norm"] = df_lc["fico_score"] / 900

In [76]:
# Delinquency Indicator
df_lc["delinquency"] = df_lc["delinq_2yrs"]
df_lc["log_delinquency"] = np.log1p(df_lc["delinq_2yrs"])
df_lc.drop(["delinq_2yrs"], axis=1, inplace=True)

In [77]:
# Log transformations
df_lc["log_loan_amount"] = np.log1p(df_lc["loan_amnt"])
df_lc["log_installment"] = np.log1p(df_lc["installment"])
df_lc["log_income"] = np.log1p(df_lc["annual_inc"].clip(
    upper=df_lc["annual_inc"].quantile(0.99)
))
df_lc["log_credit_history_length"] = np.log1p(df_lc["credit_history_length"])
df_lc["log_inquiries"] = np.log1p(df_lc["inq_last_6mths"])
df_lc["inquiries"] = df_lc["inq_last_6mths"]
df_lc.drop(["inq_last_6mths"], axis=1, inplace=True)

In [78]:
df_lc.isnull().sum().sort_values(ascending=False)

int_rate                     0
loan_amnt                    0
log_inquiries                0
log_credit_history_length    0
log_income                   0
log_installment              0
log_loan_amount              0
log_delinquency              0
delinquency                  0
credit_score_norm            0
loan_to_income               0
dti_computed                 0
credit_history_length        0
fico_score                   0
target                       0
purpose                      0
pub_rec                      0
open_acc                     0
total_acc                    0
revol_bal                    0
revol_util                   0
dti                          0
emp_length                   0
verification_status          0
annual_inc                   0
installment                  0
term                         0
inquiries                    0
dtype: int64

Transform loan_status into a clean binary target for modeling for good loan vs bad loan

In [79]:
df_lc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1373508 entries, 0 to 2260697
Data columns (total 28 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   int_rate                   1373508 non-null  float64
 1   loan_amnt                  1373508 non-null  float64
 2   term                       1373508 non-null  int64
 3   installment                1373508 non-null  float64
 4   annual_inc                 1373508 non-null  float64
 5   verification_status        1373508 non-null  object
 6   emp_length                 1373508 non-null  float64
 7   dti                        1373508 non-null  float64
 8   revol_util                 1373508 non-null  float64
 9   revol_bal                  1373508 non-null  float64
 10  total_acc                  1373508 non-null  float64
 11  open_acc                   1373508 non-null  float64
 12  pub_rec                    1373508 non-null  float64
 13  purpose                    1373508 non-null  object
 14  target                     1373508 non-null  int64
 15  fico_score                 1373508 non-null  float64
 16  credit_history_length      1373508 non-null  float64
 17  dti_computed               1373508 non-null  float64
 18  loan_to_income             1373508 non-null  float64
 19  credit_score_norm          1373508 non-null  float64
 20  delinquency                1373508 non-null  float64
 21  log_delinquency            1373508 non-null  float64
 22  log_loan_amount            1373508 non-null  float64
 23  log_installment            1373508 non-null  float64
 24  log_income                 1373508 non-null  float64
 25  log_credit_history_length  1373508 non-null  float64
 26  log_inquiries              1373508 non-null  float64
 27  inquiries                  1373508 non-null  float64
dtypes: float64(24), int64(2), object(2)
memory usage: 303.9+ MB

In [80]:
df_lc.describe()

,int_rate,loan_amnt,term,installment,annual_inc,emp_length,dti,revol_util,revol_bal,total_acc,...,loan_to_income,credit_score_norm,delinquency,log_delinquency,log_loan_amount,log_installment,log_income,log_credit_history_length,log_inquiries,inquiries
count,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,...,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06,1.373508e+06
mean,1.328534e+01,1.445720e+04,4.186296e+01,4.389718e+02,7.628202e+04,5.630152e+00,1.830763e+01,5.177206e+01,1.624851e+04,2.494231e+01,...,2.197193e-01,7.756554e-01,3.185653e-01,1.738581e-01,9.369440e+00,5.896020e+00,1.108087e+01,3.298559e+00,3.803842e-01,6.615564e-01
std,4.787062e+00,8.742497e+03,1.031197e+01,2.621425e+02,7.026271e+04,3.832357e+00,1.132211e+01,2.453097e+01,2.242656e+04,1.200980e+01,...,1.105201e+00,3.534180e-02,8.798839e-01,3.861987e-01,6.970657e-01,6.561547e-01,5.285932e-01,2.614596e-01,4.775294e-01,9.586877e-01
min,5.310000e+00,5.000000e+02,3.600000e+01,4.930000e+00,1.600000e+01,-1.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,...,1.714285e-04,6.800000e-01,0.000000e+00,0.000000e+00,6.216606e+00,1.780024e+00,2.833213e+00,2.440559e+00,0.000000e+00,0.000000e+00
25%,9.750000e+00,8.000000e+03,3.600000e+01,2.488800e+02,4.576000e+04,2.000000e+00,1.179000e+01,3.340000e+01,5.926000e+03,1.600000e+01,...,1.249969e-01,7.466667e-01,0.000000e+00,0.000000e+00,8.987322e+00,5.520981e+00,1.073119e+01,3.123993e+00,0.000000e+00,0.000000e+00
50%,1.279000e+01,1.200000e+04,3.600000e+01,3.754300e+02,6.500000e+04,6.000000e+00,1.763000e+01,5.210000e+01,1.111700e+04,2.300000e+01,...,1.999956e-01,7.688889e-01,0.000000e+00,0.000000e+00,9.392745e+00,5.930732e+00,1.108216e+01,3.282969e+00,0.000000e+00,0.000000e+00
75%,1.602000e+01,2.000000e+04,3.600000e+01,5.817700e+02,9.000000e+04,1.000000e+01,2.408000e+01,7.070000e+01,1.973600e+04,3.200000e+01,...,2.916606e-01,7.911111e-01,0.000000e+00,0.000000e+00,9.903538e+00,6.367793e+00,1.140758e+01,3.462992e+00,6.931472e-01,1.000000e+00
max,3.099000e+01,4.000000e+04,6.000000e+01,1.719830e+03,1.099920e+07,1.000000e+01,9.990000e+02,8.923000e+02,2.904836e+06,1.760000e+02,...,8.000000e+02,9.416667e-01,3.900000e+01,3.688879e+00,1.059666e+01,7.450562e+00,1.243719e+01,4.532982e+00,3.526361e+00,3.300000e+01

In [81]:
df_lc.head()

,int_rate,loan_amnt,term,installment,annual_inc,verification_status,emp_length,dti,revol_util,revol_bal,...,loan_to_income,credit_score_norm,delinquency,log_delinquency,log_loan_amount,log_installment,log_income,log_credit_history_length,log_inquiries,inquiries
0,13.99,3600.0,36,123.03,55000.0,Not Verified,10.0,5.91,29.7,2765.0,...,0.065453,0.752222,0.0,0.000000,8.188967,4.820523,10.915107,3.163566,0.693147,1.0
1,11.99,24700.0,36,820.28,65000.0,Not Verified,10.0,16.06,19.2,21470.0,...,0.379994,0.796667,1.0,0.693147,10.114599,6.710864,11.082158,3.307739,1.609438,4.0
2,10.78,20000.0,60,432.66,63000.0,Not Verified,10.0,10.78,56.2,7869.0,...,0.317455,0.774444,0.0,0.000000,9.903538,6.072261,11.050906,3.282969,0.000000,0.0
4,22.45,10400.0,60,289.91,104433.0,Source Verified,3.0,25.37,64.5,21929.0,...,0.099584,0.774444,1.0,0.693147,9.249657,5.673014,11.556311,3.361231,1.386294,3.0
5,13.44,11950.0,36,405.18,34000.0,Source Verified,4.0,10.20,68.4,8822.0,...,0.351460,0.768889,0.0,0.000000,9.388570,6.006796,10.434145,3.676266,0.000000,0.0

In [82]:
df_lc.to_csv('../../data/processed/cleaned_lending-club-car-loan.csv')